### ISSUE TITLE
Installing jas version 1.0.0

### ISSUE THREAD

**Issue by gand07** [bellrichm/weewx-jas#120]
I have just uninstalled the master version, my mistake, and now I have installed version 1.0.0 and I still have an empty jas webpage,

I'm running:
WeeWx Version 4.10.2 
Ubuntu version:20.04.6 LTS 
Phyton version:3.8.10

I have added this to weewx.conf:
[[jas]]
        skin = jas
	HTML_ROOT = public_html/argon1.billeder.de
        enable = true
	unit_system = METRICWX

I need to add unit_system, otherwise I got this error. See unit_error.txt

I have attached output from syslog. See output.txt

I have attached the jas webpage.. See jas1.jpg

Thanks

Gert
![jas1](https://github.com/bellrichm/weewx-jas/assets/47734099/9aa906df-dabe-4323-9a85-97292f879fff)
[output.txt](https://github.com/bellrichm/weewx-jas/files/12423231/output.txt)
[unit_error.txt](https://github.com/bellrichm/weewx-jas/files/12423232/unit_error.txt)

**Comment by bellrichm** [comment]
No apology necessary. I like to have people install the released code because then I know exactly what they have. Since you installed from master, I’ve already updated it with other fixes (which in theory should not affect your problem - but until tested, I cannot be sure). Thanks for installing 1.0.0.
I’m puzzled about the unit_system error and will be trying to recreate that first.
Since it is a new install, if you are comfortable attaching your weewx.conf - that would help. Or at least everything under [StdReport]. Be sure to double check for any sensitive information. 
Thanks!

**Comment by bellrichm** [comment]
It appears your installation is not setting default values for `unit_system` and `lang`.  Not sure why.
I plan to update WeeWX-jas to set `unit_system = us` if for some reason the WeeWX default is not set.
I plan to ‘error out’ if `lang` is not set. This is because I cannot guess a default for this setting.
Until I get the code updated an released, a work around is to set `lang = en`.

```
[[jas]]
    skin = jas
    HTML_ROOT = public_html/argon1.billeder.de
    enable = true
    unit_system = METRICWX
    lang = en
```

**Comment by gand07** [comment]
Hi

That was it, up and running. T hank you for your effort

Gert

**Comment by bellrichm** [comment]
Thanks for the update!
I am puzzled that your install is missing WeeWX defaults. Next update will handle this better.
Thanks for the help!
