### ISSUE TITLE
getDataday_ is not defined

### ISSUE THREAD

**Issue by hoetzgit** [bellrichm/weewx-jas#133]
Hello Rich,

I get the following error in my browser:

```
Uncaught ReferenceError: getDataday_ is not defined
    at handleDataLoaded (day.js:662:1)
    at day.js:797:29
```

Henry

**Edit**: I also get error messages in the browser with other routines. Maybe I have my own configuration errors? You can test this by clicking on the tabs on the following page and viewing the error messages:

[my page](https://jas.weiherhammer-wetter.de)

**Comment by bellrichm** [comment]
Thanks for testing and the report. I am guessing that this is due to #132.  I am sure that you noticed the timing information in the console. I thought about removing this, but it might interesting for me to see what the performance I see when running from your site. v1.1 was a complete rewrite of managing the data. It should perform better, or at least appear to.

**Comment by bellrichm** [comment]
I believe this is fixed. Feel free to re-open or open another issue if you are still seeing the problem.
